/* --
      LIST OF Enums
      They cannot be created inside a class.
-- */

/// Switch of Custom Brand-Text-Size Widget
enum TextSizes { small, medium, large }

enum Category {
  foodAndDining,
  transportation,
  housing,
  entertainment,
  utilities,
  healthcare,
  education,
  personalCare,
  travel,
  giftsAndDonations,
  savingsInvestments,
  insurance,
  taxes,
  debtPayments,
  businessExpense,
  miscellaneous,
  shopping,
  clothing,
  electronics,
  homeImprovement,
  subscriptions,
  childcare,
  petCare,
  automotive,
  fitness,
  beauty,
  hobbies,
  booksAndMagazines,
  sportingGoods,
  homeDecor,
  gardening,
  music,
  artAndCrafts,
  groceries
}

const categoryType = {
  Category.foodAndDining: "Food and Dining",
  Category.transportation: "Transportation",
  Category.housing: "Housing",
  Category.entertainment: "Entertainment",
  Category.utilities: "Utilities",
  Category.healthcare: "Healthcare",
  Category.education: "Education",
  Category.personalCare: "Personal Care",
  Category.travel: "Travel",
  Category.giftsAndDonations: "Gifts and Donations",
  Category.savingsInvestments: "Savings and Investments",
  Category.insurance: "Insurance",
  Category.taxes: "Taxes",
  Category.debtPayments: "Debt Payments",
  Category.businessExpense: "Business Expense",
  Category.miscellaneous: "Miscellaneous",
  Category.shopping: "Shopping",
  Category.clothing: "Clothing",
  Category.electronics: "Electronics",
  Category.homeImprovement: "Home Improvement",
  Category.subscriptions: "Subscriptions",
  Category.childcare: "Childcare",
  Category.petCare: "Pet Care",
  Category.automotive: "Automotive",
  Category.fitness: "Fitness",
  Category.beauty: "Beauty",
  Category.hobbies: "Hobbies",
  Category.booksAndMagazines: "Books and Magazines",
  Category.sportingGoods: "Sporting Goods",
  Category.homeDecor: "Home Decor",
  Category.gardening: "Gardening",
  Category.music: "Music",
  Category.artAndCrafts: "Art and Crafts",
  Category.groceries: "Groceries",
};
