import 'package:flutter/material.dart';

import 'package:unicons/unicons.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

/* --
      LIST OF Enums
      They cannot be created inside a class.
-- */

/// Switch of Custom Brand-Text-Size Widget
enum TextSizes { small, medium, large }

const Map<String, String> categories = {
  "foodAndDining": "Food and Dining",
  "groceries": "Groceries",
  "transportation": "Transportation",
  "housing": "Housing",
  "entertainment": "Entertainment",
  "utilities": "Utilities",
  "healthcare": "Healthcare",
  "education": "Education",
  "personalCare": "Personal Care",
  "travel": "Travel",
  "giftsAndDonations": "Gifts and Donations",
  "savingsInvestments": "Savings and Investments",
  "insurance": "Insurance",
  "taxes": "Taxes",
  "debtPayments": "Debt Payments",
  "businessExpense": "Business Expense",
  "miscellaneous": "Miscellaneous",
  "shopping": "Shopping",
  "clothing": "Clothing",
  "electronics": "Electronics",
  "homeImprovement": "Home Improvement",
  "subscriptions": "Subscriptions",
  "childcare": "Childcare",
  "petCare": "Pet Care",
  "automotive": "Automotive",
  "fitness": "Fitness",
  "beauty": "Beauty",
  "hobbies": "Hobbies",
  "booksAndMagazines": "Books and Magazines",
  "sportingGoods": "Sporting Goods",
  "homeDecor": "Home Decor",
  "gardening": "Gardening",
  "music": "Music",
  "artAndCrafts": "Art and Crafts",
  "officeSupplies": "Office Supplies",
  "phone": "Phone",
  "internet": "Internet",
  "streamingServices": "Streaming Services",
  "charity": "Charity",
  "diningOut": "Dining Out",
  "alcohol": "Alcohol",
  "lottery": "Lottery",
  "parking": "Parking",
  "tolls": "Tolls",
  "medicalSupplies": "Medical Supplies",
  "therapy": "Therapy",
  "veterinary": "Veterinary",
  "babySupplies": "Baby Supplies",
  "schoolSupplies": "School Supplies",
  "tuition": "Tuition",
  "bankFees": "Bank Fees",
  "creditCardFees": "Credit Card Fees",
  "laundry": "Laundry",
  "cleaning": "Cleaning",
  "storage": "Storage",
  "repairs": "Repairs",
  "maintenance": "Maintenance",
};

const Map<String, IconData> categoryIcons = {
  "foodAndDining": UniconsLine.utensils,
  "groceries": UniconsLine.shopping_cart,
  "transportation": UniconsLine.bus,
  "housing": UniconsLine.home,
  "entertainment": UniconsLine.tv_retro,
  "utilities": UniconsLine.bolt,
  "healthcare": UniconsLine.heart,
  "education": UniconsLine.book,
  "personalCare": UniconsLine.user_circle,
  "travel": UniconsLine.plane,
  "giftsAndDonations": UniconsLine.gift,
  "savingsInvestments": UniconsLine.money_stack,
  "insurance": UniconsLine.shield_check,
  "taxes": UniconsLine.dollar_sign,
  "debtPayments": UniconsLine.bill,
  "businessExpense": UniconsLine.briefcase,
  "miscellaneous": UniconsLine.apps,
  "shopping": UniconsLine.shopping_bag,
  "clothing": FontAwesomeIcons.shirt,
  "electronics": UniconsLine.mobile_android,
  "homeImprovement": UniconsLine.wrench,
  "subscriptions": UniconsLine.file_contract,
  "childcare": UniconsLine.baby_carriage,
  "petCare": FontAwesomeIcons.dog,
  "automotive": UniconsLine.car,
  "fitness": UniconsLine.dumbbell,
  "beauty": UniconsLine.diamond,
  "hobbies": UniconsLine.puzzle_piece,
  "booksAndMagazines": UniconsLine.books,
  "sportingGoods": UniconsLine.basketball,
  "homeDecor": UniconsLine.paint_tool,
  "gardening": UniconsLine.flower,
  "music": UniconsLine.music,
  "artAndCrafts": UniconsLine.paint_tool,
  "officeSupplies": UniconsLine.paperclip,
  "phone": UniconsLine.phone,
  "internet": UniconsLine.globe,
  "streamingServices": UniconsLine.play_circle,
  "charity": FontAwesomeIcons.handshake,
  "diningOut": UniconsLine.utensils_alt,
  "alcohol": FontAwesomeIcons.wineBottle,
  "lottery": UniconsLine.trophy,
  "parking": UniconsLine.parking_circle,
  "tolls": UniconsLine.money_insert,
  "medicalSupplies": UniconsLine.medkit,
  "therapy": UniconsLine.smile_beam,
  "veterinary": UniconsLine.heart_rate,
  "babySupplies": UniconsLine.baby_carriage,
  "schoolSupplies": UniconsLine.book_open,
  "tuition": UniconsLine.graduation_cap,
  "bankFees": FontAwesomeIcons.piggyBank,
  "creditCardFees": UniconsLine.credit_card,
  "laundry": FontAwesomeIcons.shirt,
  "cleaning": FontAwesomeIcons.broom,
  "storage": UniconsLine.box,
  "repairs": UniconsLine.wrench,
  "maintenance": UniconsLine.cog,
};

const Map<String, Color> categoryColors = {
  "foodAndDining": Colors.red,
  "groceries": Colors.green,
  "transportation": Colors.blue,
  "housing": Colors.brown,
  "entertainment": Colors.purple,
  "utilities": Colors.yellow,
  "healthcare": Colors.pink,
  "education": Colors.orange,
  "personalCare": Colors.teal,
  "travel": Colors.indigo,
  "giftsAndDonations": Colors.cyan,
  "savingsInvestments": Colors.amber,
  "insurance": Colors.lime,
  "taxes": Colors.deepOrange,
  "debtPayments": Colors.deepPurple,
  "businessExpense": Colors.lightBlue,
  "miscellaneous": Colors.lightGreen,
  "shopping": Colors.blueGrey,
  "clothing": Colors.redAccent,
  "electronics": Colors.greenAccent,
  "homeImprovement": Colors.blueAccent,
  "subscriptions": Colors.yellowAccent,
  "childcare": Colors.orangeAccent,
  "petCare": Colors.pinkAccent,
  "automotive": Colors.purpleAccent,
  "fitness": Colors.cyanAccent,
  "beauty": Colors.amberAccent,
  "hobbies": Colors.limeAccent,
  "booksAndMagazines": Colors.tealAccent,
  "sportingGoods": Colors.deepOrangeAccent,
  "homeDecor": Colors.deepPurpleAccent,
  "gardening": Colors.lightBlueAccent,
  "music": Colors.lightGreenAccent,
  "artAndCrafts": Colors.blueGrey,
  "officeSupplies": Colors.red,
  "phone": Colors.green,
  "internet": Colors.blue,
  "streamingServices": Colors.brown,
  "charity": Colors.purple,
  "diningOut": Colors.yellow,
  "alcohol": Colors.pink,
  "lottery": Colors.orange,
  "parking": Colors.teal,
  "tolls": Colors.indigo,
  "medicalSupplies": Colors.cyan,
  "therapy": Colors.amber,
  "veterinary": Colors.lime,
  "babySupplies": Colors.deepOrange,
  "schoolSupplies": Colors.deepPurple,
  "tuition": Colors.lightBlue,
  "bankFees": Colors.lightGreen,
  "creditCardFees": Colors.blueGrey,
  "laundry": Colors.redAccent,
  "cleaning": Colors.greenAccent,
  "storage": Colors.blueAccent,
  "repairs": Colors.yellowAccent,
  "maintenance": Colors.orangeAccent,
};
