name: moniito_v2
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  lottie: ^2.7.0
  shimmer: ^3.0.0
  logger: ^2.0.2+1
  flutter_svg: ^2.0.9
  image_picker: ^1.0.4
  image_cropper: ^7.0.4
  photo_view: ^0.15.0
  url_launcher: ^6.2.1
  connectivity_plus: ^5.0.1
  cached_network_image: ^3.3.0
  flutter_native_splash: ^2.3.5
  smooth_page_indicator: ^1.1.0
  fl_chart: ^0.68.0
  

  # Icons
  iconsax: ^0.0.8
  unicons: ^2.1.1
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  firebase_storage: ^11.5.1
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^6.0.2
  
    #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/images/content/
    - assets/images/logos/
    - assets/images/animations/
    - assets/images/on_boarding_images/

  #--------------- LOCAL FONTS ------------------#
  fonts: 
    - family: Uber Move
      fonts:
        - asset: assets/fonts/UberMove-Light.ttf
          weight: 300
        - asset: assets/fonts/UberMove-Regular.ttf
          weight: 400
        - asset: assets/fonts/UberMove-Medium.ttf
          weight: 500
        - asset: assets/fonts/UberMove-Bold.ttf
          weight: 800
    
    - family: iconsax
      fonts:
        - asset: assets/fonts/iconsax.ttf