// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO8-6eq4Hp4NmzA6Vo8yWicuqHUxtn0xo',
    appId: '1:478038809355:android:2de6f7f27d69a219fc200e',
    messagingSenderId: '478038809355',
    projectId: 'moniito-v1',
    storageBucket: 'moniito-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrgO2z31x5ax2vpy_nw6JiLs8vWKAOifc',
    appId: '1:478038809355:ios:9a4fba44d040f042fc200e',
    messagingSenderId: '478038809355',
    projectId: 'moniito-v1',
    storageBucket: 'moniito-v1.appspot.com',
    androidClientId: '478038809355-kih3quee0s4kn1ajnn7vqejjl730p5qa.apps.googleusercontent.com',
    iosClientId: '478038809355-dn1tccsogea4ol21jdgo0potcocseapq.apps.googleusercontent.com',
    iosBundleId: 'com.example.moniitoV2',
  );

}